version: '3.1'

services:
  db:
    image: postgres
    restart: always
#    volumes:
#      - ./sql:/docker-entrypoint-initdb.d
#      - ./.data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432